#!/usr/bin/env python3
"""
Setup script for Crypto Analysis Pro
This script helps you configure the application with your API keys.
"""

import os
import streamlit as st

def create_secrets_file():
    """Create the secrets.toml file with user input"""
    
    print("🔧 Crypto Analysis Pro Setup")
    print("=" * 40)
    
    # Get API keys from user
    coingecko_key = input("Enter your CoinGecko API key (or press Enter to skip): ").strip()
    fred_key = input("Enter your FRED API key (or press Enter to skip): ").strip()
    
    # Create .streamlit directory if it doesn't exist
    os.makedirs(".streamlit", exist_ok=True)
    
    # Create secrets.toml file
    secrets_content = f"""# Streamlit Secrets Configuration
# Generated by setup.py

# CoinGecko API Key
COINGECKO_API_KEY = "{coingecko_key if coingecko_key else 'your_coingecko_api_key_here'}"

# FRED API Key
FRED_API_KEY = "{fred_key if fred_key else 'your_fred_api_key_here'}"
"""
    
    with open(".streamlit/secrets.toml", "w") as f:
        f.write(secrets_content)
    
    print("\n✅ Configuration saved to .streamlit/secrets.toml")
    
    if coingecko_key:
        print("🔑 CoinGecko API key configured")
    else:
        print("⚠️  No CoinGecko API key provided - using free tier")
    
    if fred_key:
        print("🔑 FRED API key configured")
    else:
        print("⚠️  No FRED API key provided - economic data will be limited")
    
    print("\n🚀 You can now run: streamlit run app.py")

if __name__ == "__main__":
    create_secrets_file()
